# Contains model configs.
sampling_rate: &sampling_rate 22050
mel_channels: &mel_channels 80

trainer:
  sampling_rate: *sampling_rate

  audio_generator:
    _target_: models.AudioGenerator
    align_gamma: 10.0
    encoder_layers: 8
    encoder_channels: 256
    decoder_scales: [2, 3, 3, 5]
    decoder_channels: 256
    latent_channels: 256
    kernel_size: 3

  audio_discriminator:
    _target_: models.AudioDiscriminator
    windows: [200, 400, 800, 1600, 3200]
    n_layers: 4
    base_channels: 64
    kernel_size: 3

  spect_discriminator:
    _target_: models.SpectrogramDiscriminator
    n_discs: 3
    n_layers: 4
    mel_channels: *mel_channels
    base_channels: 64
    kernel_size: 3

  spect_fn:
    _target_: modules.mel.MelSpectrogram
    filter_length: 1024
    hop_length: 256
    win_length: 1024
    n_mels: *mel_channels
    sampling_rate: *sampling_rate
    mel_fmin: 0.
    mel_fmax: 8000.
    window: hann

  sdtw_fn:
    _target_: modules.sdtw.SoftDynamicTimeWarping
    gamma: 0.01
    penalty: 1.0
    normalize: false
    bandwidth: null
    dist_func: manhattan
